//
//  ListOfAffirmations.swift
//  iMatter
//
//  Created by Mycah on 1/18/20.
//  Copyright © 2020 Mycah Krason. All rights reserved.
//

import Foundation

struct ListOfAffirmations{
    
    var listOfAllAffirmations : [String] = [
        "I am successful in whatever I do",
        "I plan my work and work my plan",
        "I focus on what is truly essential",
        "I will make the most of new opportunities",
        "Good flows to me, good flows from me",
        "I feel wonderful and alive",
        "I feel the joy of abundance",
        "I speak with confidence and calm assurance",
        "The universe provides for my every want and need",
        "I am healthy and happy",
        "I have a lot of energy",
        "I radiate happiness",
        "Everything is getting better every day",
        "My mind is calm",
        "I am always on the path of success & victory",
        "I am at peace with myself",
        "I find peace and joy in all aspects of my life",
        "I have value and I matter",
        "I am a success in all that I do",
        "I am happy",
        "I feel joy, love, and abundance",
        "I am one with my inner child",
        "I am amazing",
        "I can do anything",
        "I am prepared to succeed",
        "Positivity is a choice",
        "I am fabulous, funny, and giving",
        "I am outstanding",
        "I am unique, special and most importantly I am me",
        "I am financially free",
        "I am perfect exactly as I am",
        "I focus on what is truly essential",
        "I make positive healthy choices",
        "I am in control of my reactions",
        "I find all solutions within me",
        "All is well in my life",
        "I will make the most of new opportunities",
        "I organize my priorities with clarity",
        "I forgive myself",
        "I am forgiven",
        "I will always be there for myself",
        "I enjoy the variety of life",
        "I am my own guru",
        "I take good care of myself",
        "I am patient with myself",
        "I let go of my past",
        "I am evolving eternally",
        "I know I can always upgrade",
        "There is a gift for me in everything that I experience",
        "I follow my inner guidance",
        "I appreciate my physical body",
        "I treat my body well",
        "I take it easy",
        "I make room for fun and playfulness",
        "I appreciate intimacy",
        "I am very good at letting go",
        "I am grateful for my life",
        "I love being myself",
        "Time is on my side",
        "I surrender to love",
        "I invite bliss",
        "I learn from my past",
        "I am good at walking the talk",
        "I enjoy being taken good care of by the universe",
        "I create my reality on a continuous basis",
        "My body is healthy",
        "I am superior to negative thoughts and low actions",
        "I forgive those who have harmed me in my past and peacefully detach from them",
        "I possess the qualities needed to be extremely successful",
        "My business is growing, expanding, and thriving",
        "My ability to conquer my challenges is limitless",
        "My potential to succeed is infinite",
        "I am courageous and I stand up for myself",
        "My thoughts are filled with positivity and my life is plentiful with prosperity",
        "I am blessed with an incredible family and wonderful friends",
        "I am a powerhouse",
        "My future is an ideal projection of what I envision now",
        "I radiate beauty, charm, and grace",
        "I am conquering my illness",
        "I wake up today with strength in my heart and clarity in my mind",
        "My fears of tomorrow are simply melting away",
        "My life is just beginning",
        "The assertion that something exists or is true",
        "I always have everything I need to be happy",
        "I live a positive life and only attract the best in my life",
        "I am peacefully allowing my life to unfold",
        "Today, and every day, I choose to be happy",
        "I am fun energetic and people love me for it",
        "My life overflows with happiness and love",
        "Today is rich with opportunity and I open my heart to receive them",
        "I take the time to show my friends that I care about them",
        "I am thankful that I get to live another day",
        "I see the world with beauty and color",
        "I deserve whatever good comes my way today",
        "I believe in myself",
        "I radiate confidence, certainty and optimism",
        "I courageously open and move through every door of opportunity",
        "I am in charge of my life",
        "I have the power to love my dreams",
        "My mind has unlimited power",
        "I stand up for what I believe in",
        "I act with courage and confidence",
        "I love myself more everyday",
        "I am blessed with an incredible family and wonderful friends",
        "I will continue to learn and grow",
        "Everything will work out for me",
        "I am a winner",
        "The tools I need to succeed are in my possession",
        "There is nobody better to get the job done than me",
        "I have faith in my social skills",
        "I am beautiful",
        "I am smart",
        "I am blessed with talents",
        "I am stronger than any storm",
        "I deserve my dreams",
        "I am worthy of genuine love",
        "I am a leader",
        "Unconditional love flows to me",
        "I am worthy of respect",
        "My features are beautiful",
        "I greet each day with strength",
        "I deserve to feel strong",
        "I am free of self doubt",
        "I’ve got this",
        "No matter what comes my way, I can do it",
        "I am overflowing with achievement",
        "I am fearless",
        "I face every challenge with a smile",
        "I’m unstoppable",
        "I believe in my abilities",
        "Other people will not take advantage of me",
        "I have confidence in my skills",
        "I am not afraid to be wrong",
        "Happiness is within my grasp",
        "I am confident in the presence of others",
        "Success will be my driving force",
        "The success of others will not make me jealous. My time will come",
        "I will speak with confidence and self-assurance",
        "I will say “No” when I do not have the time or inclination to act",
        "The only person who can defeat me is myself",
        "I am stronger than negative thoughts",
        "I deserve the compliments I am given",
        "Today, I will be positive",
        "Obstacles are merely challenges to overcome",
        "I am powerful, confident, and capable of achieving my goals",
        "In every struggle lies a learning experience",
        "I embrace my individuality",
        "I believe in myself completely",
        "I trust myself",
        "My dreams are possible",
        "I respect my limitations and I am grateful for the capabilities I do have",
        "I am not my mistakes",
        "I am successful",
        "I choose happiness",
        "I have all I need to make today a great day",
        "I inhale confidence and exhale fear",
        "I love myself as I am",
        "I am loved, I am brave, I am good enough",
        "I have nothing to prove to anyone",
        "I am fully committed to achieving my goals",
        "I believe in myself and my ability to succeed",
        "I am capable of handling anything",
        "I have enough, I do enough, I am enough",
        "I love to make new friends",
        "I am fearless",
        "I am happy",
        "I am safe",
        "I am worthy",
        "I am strong",
        "I am loved",
        "I will help somebody today",
        "I am grateful for today",
        "Today is a day of happiness and peace",
        "I will strive to be a better person today",
        "Today, I will be kind",
        "I am enough",
        "I won’t hold grudges",
        "I am ready for the challenges I will face today",
        "Something wonderful will happen today",
        "I am wise enough to make the right choices",
        "I am confident",
        "I deserve my place in this world",
        "I am capable",
        "I will face my fears",
        "I will learn from my mistakes",
        "I will be proud of my accomplishments",
        "I can do anything I want to do",
        "My heart is open to love and joy",
        "I will not give up",
        "I embrace the new",
        "I will do my best today",
        "I am blessed to be happy and healthy",
        "I am thankful for my loved ones today",
        "Today I will learn and grow",
        "Today is full of possibilities",
        "I am filled with energy today",
        "I will only attract good things today",
        "I am free to be myself today",
        "Today is my day to shine",
        "I am open to all of the opportunities I am sent today",
        "I dare to be different",
        "My every desire is achievable",
        "Even outside my comfort zone, I will be comfortable in my own skin",
        "If I fail, I will fail forward",
        "My confidence knows no limits",
        "I do not need other people for happiness",
        "I choose hope over fear",
        "Positivity is a choice that I choose to make",
        "I will not take other people's negativity personally",
        "My commitment to myself is real",
        "Today, I choose me",
        "I am worthy of infinite compassion",
        "I feel profound empathy and love for others and their own unique paths",
        "I choose to stop apologizing for being me",
        "I am at peace with all that has happened in my life",
        "My life is filled with joy and abundance",
        "Happiness flows from me",
        "I am willing to keep going when things get tough, to achieve the success I deserve",
        "My body is beautiful and expresses my spirit",
        "I am grounded, peaceful, and centered",
        "I respect my limitations and thank myself for the things I am able to accomplish",
        "My life is full of happiness and love",
        "I feel pride in myself",
        "I am not the sum of my mistakes",
        "I have everything I need",
        "I feel beautiful, I am beautiful",
        "I am empowered to create change in my life",
        "I will focus on the bright side",
        "I am blessed",
        "I follow my own expectations, not the expectations of others",
        "I am in control of my own actions",
        "I overflow with creativity and good ideas",
        "I do not judge myself or others",
        "I did not get up today to “just” be average. I will excel",
        "I am not my negative thoughts or emotions",
        "I am increasing my prosperity every day",
        "I am confident and strong",
        "I deserve love",
        "My inner beauty shines brightly",
        "I am enough",
        "My confidence is soaring",
        "I am who I need to be",
        "I am more than my body",
        "I celebrate my many successes",
        "I will not take criticism personally",
        "I have a caring heart",
        "I love the person I am becoming",
        "I deserve the good that happens to me",
        "Negativity has no place in my life",
        "My decisions are based on inner wisdom",
        "I am a diamond-in-the-rough, all I need is some polishing",
        "Self-love comes to me with ease",
        "I embrace my flaws, knowing no one is perfect",
        "I have a caring heart",
        "I have all I need to live a happy life",
        "My struggles are just opportunities to learn",
        "My individuality is important",
        "I will be assertive when I need to be",
        "I am becoming the person I want to be",
        "I have the tools I need to achieve my dreams",
        "When I practice self-love, I become more lovable",
        "The universe conspires to help me succeed",
        "I deserve good things",
        "I control my fears, they do not control me",
        "I love the person that I am",
        "I am whole alone",
        "Today, I choose myself",
        "I have faith in my abilities",
        "My life is full of love",
        "I will stand my ground and defend myself",
        "I respect myself",
        "I have worth and inner beauty",
        "I will care for myself as much as I care for others",
        "I believe in me",
        "I acknowledge my self-worth–my confidence is soaring",
        "I am not my mistakes",
        "I accept myself unconditionally",
        "I am proud of myself and all that I have accomplished",
        "I am successful",
        "I am a beautiful person",
        "I deserve love, compassion, and empathy",
        "I am enough",
        "I believe in the person I dream of becoming",
        "I choose to be happy and completely love myself today",
        "I honor my commitments to myself",
        "I choose faith over fear",
        "There is no wrong decision",
        "I am now creating my life exactly as I want it",
        "Positivity is a choice; I choose to be positive",
        "I am free of worry and am at peace with who I am",
        "I matter.  I am allowed to say “no” to others and “yes to myself",
        "What I give is what I receive",
        "I choose not to take it personally",
        "I am a diamond. It is time for me to shine",
        "My opinion matters",
        "I am a magnet for love",
        "Self-love is a natural state of being",
        "I am loved, and I am wanted",
        "I will stop apologizing for being myself",
        "Negative self-talk has no place in my life",
        "I do not bow to my fears",
        "My mind, body, and soul are fit and strong",
        "I am grateful for the things I have",
        "I act with courage and confidence",
        "I am a do-er. I will take action and get things accomplished",
        "I find the work I need to do to be  fascinating",
        "For today , I am truly attentive on my work",
        "I will be observant and attentive throughout my entire day",
        "I can focus and concentrate at will",
        "I release negativity. Instead I focus on positivity and productivity",
        "I have clarity and energy",
        "I am committed to being focus on my goal. I am worth it",
        "I concentrate all my efforts on the things I want to accomplish in life",
        "I can work my way into the flow state whenever I wish",
        "I am calm and focused in all that I do",
        "Today I will take a big step toward reaching my goals",
        "All resistance achieving my goal has vanished",
        "I know where I am going. I only need to supply the action to get there",
        "My mind is energized, clear and focused on the process of my goals",
        "I free myself from the doubt and pessimism that keep me from achieving my goals",
        "I clearly visualize the attainment of my goals",
        "Giving up is easy. I will continue striving for my goals",
        "I clearly see the obstacles to keep me from achieving my goals I move over, under, through or around them",
        "My planning, action and hard work will translate to the achievement of my desires",
        "My daily goals will ensure I reach my long term goals",
        "I will face my fears head on and I will learn from them",
        "I will achieve all of my goals",
        "My goals are simple and uncomplicated",
        "Clients will flock to me",
        "My goals are getting closer to completion every day",
        "I set clear goals and work to complete them every day",
        "I am worthy of manifesting my biggest desires",
        "I believe in myself and my ability to succeed",
        "something wonderful is about to happen to me",
        "I allow love to fill me up and guide me in all of my actions",
        "Everything is alway working out for me",
        "I always choose happiness",
        "My mind is free of resistance and open to the possibilities",
        "I am in the process of becoming the best version of myself",
        "I look for the good in every situation",
        "My desires are fueled by an unlimited belief in myself",
        "I can do anything I put my mind to",
        "I have faith in myself and in my abilities",
        "I have what it takes to reach my goals",
        "I can handle anything that comes my way",
        "Great strength lies within me at all times",
        "I have the courage to keep going",
        "I have the courage to walk my own path and follow my dreams",
        "My dreams are far more important than my fears. I keep going no matter what",
        "My faith lifts me higher than fears",
        "Today I face everything with great courage",
        "It is impossible for me to fail",
        "Today, I make magic",
        "I am creating the life of my dreams",
        "I am focused, persistent and will never quit",
        "I am totally in charge of my life",
        "Whatever I put my mind to, I achieve",
        "I am not a product of my circumstances. I am a product of my decisions",
        "My energy creates my reality. What I focus on is what I will manifest",
        "I am dedicated to living in alignment with my purpose",
        "I love the life I am creating and opportunities flow to me with ease",
        "My intuition never lets me down",
        "I always follow my heart’s path",
        "I am always being guided to living my heart’s desires",
        "I live in perfect alignment with my highest truth",
        "I trust myself and turn inward to seek my highest truth",
        "My life works beautifully as I navigate my path with grace and ease",
        "I follow my intuition and know that nothing is put before me that I can’t handle",
        "Everything feels so right; I trust I am on the right path for me",
        "I see abundance everywhere",
        "I am always attracting abundance",
        "I am open to money coming to me from new ways that I've never imagined",
        "I am connected to the endless abundance of the universe",
        "I am worthy of making more money",
        "Money comes to me easily and effortlessly",
        "I always have enough money",
        "I am grateful for what I already have and for all that I receive now",
        "I handle success with grace",
        "I am fully supported making money doing what I love",
        "It is safe for me to make money",
        "I am aligned with the energy of abundance",
        "I have a plan of action to achieve my desires",
        "My priorities are clear. I work to finish my most important tasks first",
        "My goals are my focus",
        "I only set goals that matter",
        "My focus on success is unwavering",
        "When my need is strong enough, I will find a way",
        "I am committed to becoming the person I will become",
        "My mind is like water. I will change and adjust as needed",
        "Success is in my future",
        "I will master distractions and keep my focus on my goals",
        "I believe in myself. I deserve to accomplish my goals",
        "I will take advantage of change, making the most of the opportunities it presents",
        "I am constantly improving",
        "I desire to learn new things",
        "Where others see a challenge, I see new opportunities",
        "I have a growth mindset",
        "Time is my friend. I finish all the tasks I need to finish",
        "My life is made for joy. I will live with exuberance",
        "I will be proactive in discovering obstacles to my accomplishments",
        "Mindfulness will help me get the most from my time",
        "I take responsibility for my successes and my failures",
        "I am not dependent on anyone else",
        "I follow my dreams with vigor",
        "The little things in life make all the difference",
        "I enjoy being surrounded by others",
        "My fear diminishes as I live my life with courage",
        "I can go with the flow",
        "I love myself unconditionally",
        "I am STRONG",
        "I allow only healthy and loving relationships into my life",
        "Life wants the best for me. I am OK with where I am right now",
        "I am connected and comfortable in all environments, with all people",
        "I find and enjoy the simple pleasures life is offering right now",
        "How I feel matters, therefore I concentrate on aspects of life that make me feel good",
        "My challenges bring me better opportunities",
        "My mood creates a physiological response in my body. I am peaceful and positive",
        "I am in control of my thoughts and my life",
        "I love myself and who I am",
        "I am happy, healthy, and centered",
        "Change provides me an opportunity",
        "I am calm, patient, and in control of my emotions",
        "The more I give, the more I will receive",
        "My negative thoughts and self-images are gone",
        "My strength is stronger than my anxiety",
        "I move beyond stress to peace",
        "My thoughts are positive and full of joy",
        "I am safe. I trust life, and I trust in myself",
        "My life is an adventure",
        "Good enough is good enough",
        "Feelings are not facts",
        "I have abundant energy",
        "Let go of “what if”",
        "Balance in life is what I strive for",
        "I will take time to put myself first",
        "I will act after thought, not on instinct",
        "Calm is my primary state of being",
        "I am content",
        "Principles guide me. Not a moments fancy",
        "I give myself permission to take personal time",
        "Would I expect this of anyone else",
        "I am unique and a gift to the world",
        "Anxiety will not define me",
        "I am not alone",
        "I am in control",
        "I know that this will pass",
        "I can let go of negative feelings",
        "I am safe",
        "I am strong",
        "I am worthy",
        "I am loved",
        "I can get through this",
        "I do not need to feel scared",
        "Every breath I take keeps me calm",
        "I love myself unconditionally",
        "I look toward the future with hope",
        "I acknowledge and am prepared for change",
        "I have peace within me",
        "I’ve survived this before and will survive again",
        "I will focus on the beauty around me",
        "I have the patience to overcome this",
        "I am in control of my breathing and can slow it down",
        "It is safe for me to heal and grow",
        "I will fill my mind with positive thoughts",
        "I have the power to stop this",
        "I can solve any problems I may face",
        "I will attract positive energy",
        "I am healing more each day",
        "I choose to focus and be relaxed",
        "I choose to have a positive reaction to every situation I am faced with",
        "I will have a serene life",
        "I can stay calm under pressure",
        "I will focus on my breathing",
        "My life is calm",
        "Everything is okay in my life",
        "I am better than my anxiety",
        "I am letting go of my worries",
        "I will become more relaxed every day",
        "I can relax my mind",
        "I deserve to be calm",
        "I will release all the tension I’m holding in my body",
        "I am open to the idea that my future will be bright",
        "I will work smarter, not harder",
        "I am a positive influence, and I surround myself with others like me",
        "Time is my most valuable asset. I guard my time carefully",
        "Balance is key. I will mix self-care with effort",
        "My progress is always moving forward",
        "I feel free to give myself the TLC I need",
        "Positive energy surrounds me",
        "I am a wonderful employee. Any company would be lucky to have me",
        "My career will be the one of my dreams",
        "When I say “no” to the wrong job, I move that much closer to the perfect career",
        "My new business income will continue to increase",
        "I am calm and confident",
        "New opportunities come easily to me",
        "I will attract positive customer",
        "When opportunity knocks, I will be prepared to answer the door",
        "Money spent comes back to me multiplied",
        "I have all the power I need to create the success I desire",
        "The universe provides bountiful opportunities for my success",
        "I refuse to be distracted from my goals and vision",
        "Every day is filled with new ideas and new possibilities",
        "Being successful comes easily to me",
        "I am worthy of financial stability",
        "I am open-minded and willing to explore any path to success",
        "Limiting beliefs have no power over me. I am optimistic and open-minded",
        "Organization comes naturally to me",
        "I control my day; I will not let my day control me",
        "My passion for business brings tangible results",
        "I will not let others impose their limitations on me",
        "I am fully committed to achieving success in my life",
        "My only limit is myself"
    ]
    
    
    
    
//    var unfilteredArrayConfidence : [String] = [
//        "I am successful in whatever I do",
//        "I plan my work and work my plan",
//        "I focus on what is truly essential",
//        "I will make the most of new opportunities",
//        "Good flows to me, good flows from me",
//        "I feel wonderful and alive",
//        "I feel the joy of abundance",
//        "I speak with confidence and calm assurance",
//        "The universe provides for my every want and need",
//        "I am healthy and happy",
//        "I have a lot of energy",
//        "I radiate happiness",
//        "Everything is getting better every day",
//        "My mind is calm",
//        "I am always on the path of success & victory",
//        "I am at peace with myself",
//        "I find peace and joy in all aspects of my life",
//        "I have value and I matter",
//        "I am a success in all that I do",
//        "I am happy",
//        "I feel joy, love, and abundance",
//        "I am one with my inner child",
//        "I am amazing",
//        "I can do anything",
//        "I am prepared to succeed",
//        "Positivity is a choice",
//        "I am fabulous, funny, and giving",
//        "I am outstanding",
//        "I am unique, special and most importantly I am me",
//        "I am financially free",
//        "I am perfect exactly as I am",
//        "I focus on what is truly essential",
//        "I make positive healthy choices",
//        "I am in control of my reactions",
//        "I find all solutions within me",
//        "All is well in my life",
//        "I will make the most of new opportunities",
//        "I organize my priorities with clarity",
//        "I forgive myself",
//        "I am forgiven",
//        "I will always be there for myself",
//        "I enjoy the variety of life",
//        "I am my own guru",
//        "I take good care of myself",
//        "I am patient with myself",
//        "I let go of my past",
//        "I am evolving eternally",
//        "I know I can always upgrade",
//        "There is a gift for me in everything that I experience",
//        "I follow my inner guidance",
//        "I appreciate my physical body",
//        "I treat my body well",
//        "I take it easy",
//        "I make room for fun and playfulness",
//        "I appreciate intimacy",
//        "I am very good at letting go",
//        "I am grateful for my life",
//        "I love being myself",
//        "Time is on my side",
//        "I surrender to love",
//        "I invite bliss",
//        "I learn from my past",
//        "I am good at walking the talk",
//        "I enjoy being taken good care of by the universe",
//        "I create my reality on a continuous basis",
//        "My body is healthy",
//        "I am superior to negative thoughts and low actions",
//        "I forgive those who have harmed me in my past and peacefully detach from them",
//        "I possess the qualities needed to be extremely successful",
//        "My business is growing, expanding, and thriving",
//        "My ability to conquer my challenges is limitless",
//        "My potential to succeed is infinite",
//        "I am courageous and I stand up for myself",
//        "My thoughts are filled with positivity and my life is plentiful with prosperity",
//        "I am blessed with an incredible family and wonderful friends",
//        "I am a powerhouse",
//        "My future is an ideal projection of what I envision now",
//        "I radiate beauty, charm, and grace",
//        "I am conquering my illness",
//        "I wake up today with strength in my heart and clarity in my mind",
//        "My fears of tomorrow are simply melting away",
//        "My life is just beginning",
//        "The assertion that something exists or is true",
//        "I always have everything I need to be happy",
//        "I live a positive life and only attract the best in my life",
//        "I am peacefully allowing my life to unfold",
//        "Today, and every day, I choose to be happy",
//        "I am fun energetic and people love me for it",
//        "My life overflows with happiness and love",
//        "Today is rich with opportunity and I open my heart to receive them",
//        "I take the time to show my friends that I care about them",
//        "I am thankful that I get to live another day",
//        "I see the world with beauty and color",
//        "I deserve whatever good comes my way today",
//        "I believe in myself",
//        "I radiate confidence, certainty and optimism",
//        "I courageously open and move through every door of opportunity",
//        "I am in charge of my life",
//        "I have the power to love my dreams",
//        "My mind has unlimited power",
//        "I stand up for what I believe in",
//        "I act with courage and confidence",
//        "I love myself more everyday",
//        "I am blessed with an incredible family and wonderful friends",
//        "I will continue to learn and grow",
//        "Everything will work out for me",
//        "I am a winner",
//        "The tools I need to succeed are in my possession",
//        "There is nobody better to get the job done than me",
//        "I have faith in my social skills",
//        "I am beautiful",
//        "I am smart",
//        "I am blessed with talents",
//        "I am stronger than any storm",
//        "I deserve my dreams",
//        "I am worthy of genuine love",
//        "I am a leader",
//        "Unconditional love flows to me",
//        "I am worthy of respect",
//        "My features are beautiful",
//        "I greet each day with strength",
//        "I deserve to feel strong",
//        "I am free of self doubt",
//        "I’ve got this",
//        "No matter what comes my way, I can do it",
//        "I am overflowing with achievement",
//        "I am fearless",
//        "I face every challenge with a smile",
//        "I’m unstoppable",
//        "I believe in my abilities",
//        "Other people will not take advantage of me",
//        "I have confidence in my skills",
//        "I am not afraid to be wrong",
//        "Happiness is within my grasp",
//        "I am confident in the presence of others",
//        "Success will be my driving force",
//        "The success of others will not make me jealous. My time will come",
//        "I will speak with confidence and self-assurance",
//        "I will say “No” when I do not have the time or inclination to act",
//        "The only person who can defeat me is myself",
//        "I am stronger than negative thoughts",
//        "I deserve the compliments I am given",
//        "Today, I will be positive",
//        "Obstacles are merely challenges to overcome",
//        "I am powerful, confident, and capable of achieving my goals",
//        "In every struggle lies a learning experience",
//        "I embrace my individuality",
//        "I believe in myself completely",
//        "I trust myself",
//        "My dreams are possible",
//        "I respect my limitations and I am grateful for the capabilities I do have",
//        "I am not my mistakes",
//        "I am successful",
//        "I choose happiness",
//        "I have all I need to make today a great day",
//        "I inhale confidence and exhale fear",
//        "I love myself as I am",
//        "I am loved, I am brave, I am good enough",
//        "I have nothing to prove to anyone",
//        "I am fully committed to achieving my goals",
//        "I believe in myself and my ability to succeed",
//        "I am capable of handling anything",
//        "I have enough, I do enough, I am enough",
//        "I love to make new friends",
//        "I am fearless",
//        "I am happy",
//        "I am safe",
//        "I am worthy",
//        "I am strong",
//        "I am loved",
//        "I will help somebody today",
//        "I am grateful for today",
//        "Today is a day of happiness and peace",
//        "I will strive to be a better person today",
//        "Today, I will be kind",
//        "I am enough",
//        "I won’t hold grudges",
//        "I am ready for the challenges I will face today",
//        "Something wonderful will happen today",
//        "I am wise enough to make the right choices",
//        "I am confident",
//        "I deserve my place in this world",
//        "I am capable",
//        "I will face my fears",
//        "I will learn from my mistakes",
//        "I will be proud of my accomplishments",
//        "I can do anything I want to do",
//        "My heart is open to love and joy",
//        "I will not give up",
//        "I embrace the new",
//        "I will do my best today",
//        "I am blessed to be happy and healthy",
//        "I am thankful for my loved ones today",
//        "Today I will learn and grow",
//        "Today is full of possibilities",
//        "I am filled with energy today",
//        "I will only attract good things today",
//        "I am free to be myself today",
//        "Today is my day to shine",
//        "I am open to all of the opportunities I am sent today",
//        "I dare to be different",
//        "My every desire is achievable",
//        "Even outside my comfort zone, I will be comfortable in my own skin",
//        "If I fail, I will fail forward",
//        "My confidence knows no limits"
//
//    ]
    
    
//    var unfilteredArraySelfLove : [String] = [
//        "I do not need other people for happiness",
//        "I choose hope over fear",
//        "Positivity is a choice that I choose to make",
//        "I will not take other people's negativity personally",
//        "My commitment to myself is real",
//        "Today, I choose me",
//        "I am worthy of infinite compassion",
//        "I feel profound empathy and love for others and their own unique paths",
//        "I choose to stop apologizing for being me",
//        "I am at peace with all that has happened in my life",
//        "My life is filled with joy and abundance",
//        "Happiness flows from me",
//        "I am willing to keep going when things get tough, to achieve the success I deserve",
//        "My body is beautiful and expresses my spirit",
//        "I am grounded, peaceful, and centered",
//        "I respect my limitations and thank myself for the things I am able to accomplish",
//        "My life is full of happiness and love",
//        "I feel pride in myself",
//        "I am not the sum of my mistakes",
//        "I have everything I need",
//        "I feel beautiful, I am beautiful",
//        "I am empowered to create change in my life",
//        "I will focus on the bright side",
//        "I am blessed",
//        "I follow my own expectations, not the expectations of others",
//        "I am in control of my own actions",
//        "I overflow with creativity and good ideas",
//        "I do not judge myself or others",
//        "I did not get up today to “just” be average. I will excel",
//        "I am not my negative thoughts or emotions",
//        "I am increasing my prosperity every day",
//        "I am confident and strong",
//        "I deserve love",
//        "My inner beauty shines brightly",
//        "I am enough",
//        "My confidence is soaring",
//        "I am who I need to be",
//        "I am more than my body",
//        "I celebrate my many successes",
//        "I will not take criticism personally",
//        "I have a caring heart",
//        "I love the person I am becoming",
//        "I deserve the good that happens to me",
//        "Negativity has no place in my life",
//        "My decisions are based on inner wisdom",
//        "I am a diamond-in-the-rough, all I need is some polishing",
//        "Self-love comes to me with ease",
//        "I embrace my flaws, knowing no one is perfect",
//        "I have a caring heart",
//        "I have all I need to live a happy life",
//        "My struggles are just opportunities to learn",
//        "My individuality is important",
//        "I will be assertive when I need to be",
//        "I am becoming the person I want to be",
//        "I have the tools I need to achieve my dreams",
//        "When I practice self-love, I become more lovable",
//        "The universe conspires to help me succeed",
//        "I deserve good things",
//        "I control my fears, they do not control me",
//        "I love the person that I am",
//        "I am whole alone",
//        "Today, I choose myself",
//        "I have faith in my abilities",
//        "My life is full of love",
//        "I will stand my ground and defend myself",
//        "I respect myself",
//        "I have worth and inner beauty",
//        "I will care for myself as much as I care for others",
//        "I believe in me",
//        "I acknowledge my self-worth–my confidence is soaring",
//        "I am not my mistakes",
//        "I accept myself unconditionally",
//        "I am proud of myself and all that I have accomplished",
//        "I am successful",
//        "I am a beautiful person",
//        "I deserve love, compassion, and empathy",
//        "I am enough",
//        "I believe in the person I dream of becoming",
//        "I choose to be happy and completely love myself today",
//        "I honor my commitments to myself",
//        "I choose faith over fear",
//        "There is no wrong decision",
//        "I am now creating my life exactly as I want it",
//        "Positivity is a choice; I choose to be positive",
//        "I am free of worry and am at peace with who I am",
//        "I matter.  I am allowed to say “no” to others and “yes to myself",
//        "What I give is what I receive",
//        "I choose not to take it personally",
//        "I am a diamond. It is time for me to shine",
//        "My opinion matters",
//        "I am a magnet for love",
//        "Self-love is a natural state of being",
//        "I am loved, and I am wanted",
//        "I will stop apologizing for being myself",
//        "Negative self-talk has no place in my life",
//        "I do not bow to my fears",
//        "My mind, body, and soul are fit and strong",
//        "I am grateful for the things I have"
//
//    ]
//
    
//    var unfilteredArrayGoalSetting : [String] = [
//        "I act with courage and confidence",
//        "I am a do-er. I will take action and get things accomplished",
//        "I find the work I need to do to be  fascinating",
//        "For today , I am truly attentive on my work",
//        "I will be observant and attentive throughout my entire day",
//        "I can focus and concentrate at will",
//        "I release negativity. Instead I focus on positivity and productivity",
//        "I have clarity and energy",
//        "I am committed to being focus on my goal. I am worth it",
//        "I concentrate all my efforts on the things I want to accomplish in life",
//        "I can work my way into the flow state whenever I wish",
//        "I am calm and focused in all that I do",
//        "Today I will take a big step toward reaching my goals",
//        "All resistance achieving my goal has vanished",
//        "I know where I am going. I only need to supply the action to get there",
//        "My mind is energized, clear and focused on the process of my goals",
//        "I free myself from the doubt and pessimism that keep me from achieving my goals",
//        "I clearly visualize the attainment of my goals",
//        "Giving up is easy. I will continue striving for my goals",
//        "I clearly see the obstacles to keep me from achieving my goals I move over, under, through or around them",
//        "My planning, action and hard work will translate to the achievement of my desires",
//        "My daily goals will ensure I reach my long term goals",
//        "I will face my fears head on and I will learn from them",
//        "I will achieve all of my goals",
//        "My goals are simple and uncomplicated",
//        "Clients will flock to me",
//        "My goals are getting closer to completion every day",
//        "I set clear goals and work to complete them every day",
//        "I am worthy of manifesting my biggest desires",
//        "I believe in myself and my ability to succeed",
//        "something wonderful is about to happen to me",
//        "I allow love to fill me up and guide me in all of my actions",
//        "Everything is alway working out for me",
//        "I always choose happiness",
//        "My mind is free of resistance and open to the possibilities",
//        "I am in the process of becoming the best version of myself",
//        "I look for the good in every situation",
//        "My desires are fueled by an unlimited belief in myself",
//        "I can do anything I put my mind to",
//        "I have faith in myself and in my abilities",
//        "I have what it takes to reach my goals",
//        "I can handle anything that comes my way",
//        "Great strength lies within me at all times",
//        "I have the courage to keep going",
//        "I have the courage to walk my own path and follow my dreams",
//        "My dreams are far more important than my fears. I keep going no matter what",
//        "My faith lifts me higher than fears",
//        "Today I face everything with great courage",
//        "It is impossible for me to fail",
//        "Today, I make magic",
//        "I am creating the life of my dreams",
//        "I am focused, persistent and will never quit",
//        "I am totally in charge of my life",
//        "Whatever I put my mind to, I achieve",
//        "I am not a product of my circumstances. I am a product of my decisions",
//        "My energy creates my reality. What I focus on is what I will manifest",
//        "I am dedicated to living in alignment with my purpose",
//        "I love the life I am creating and opportunities flow to me with ease",
//        "My intuition never lets me down",
//        "I always follow my heart’s path",
//        "I am always being guided to living my heart’s desires",
//        "I live in perfect alignment with my highest truth",
//        "I trust myself and turn inward to seek my highest truth",
//        "My life works beautifully as I navigate my path with grace and ease",
//        "I follow my intuition and know that nothing is put before me that I can’t handle",
//        "Everything feels so right; I trust I am on the right path for me",
//        "I see abundance everywhere",
//        "I am always attracting abundance",
//        "I am open to money coming to me from new ways that I've never imagined",
//        "I am connected to the endless abundance of the universe",
//        "I am worthy of making more money",
//        "Money comes to me easily and effortlessly",
//        "I always have enough money",
//        "I am grateful for what I already have and for all that I receive now",
//        "I handle success with grace",
//        "I am fully supported making money doing what I love",
//        "It is safe for me to make money",
//        "I am aligned with the energy of abundance",
//        "I have a plan of action to achieve my desires",
//        "My priorities are clear. I work to finish my most important tasks first",
//        "My goals are my focus",
//        "I only set goals that matter",
//        "My focus on success is unwavering",
//        "When my need is strong enough, I will find a way",
//        "I am committed to becoming the person I will become",
//        "My mind is like water. I will change and adjust as needed",
//        "Success is in my future",
//        "I will master distractions and keep my focus on my goals",
//        "I believe in myself. I deserve to accomplish my goals",
//        "I will take advantage of change, making the most of the opportunities it presents",
//        "I am constantly improving",
//        "I desire to learn new things",
//        "Where others see a challenge, I see new opportunities",
//        "I have a growth mindset",
//        "Time is my friend. I finish all the tasks I need to finish",
//        "My life is made for joy. I will live with exuberance",
//        "I will be proactive in discovering obstacles to my accomplishments",
//        "Mindfulness will help me get the most from my time",
//        "I take responsibility for my successes and my failures",
//        "I am not dependent on anyone else"
//
//    ]
//
    
//    var unfilteredArrayAnxiety : [String] = [
//        "I follow my dreams with vigor",
//        "The little things in life make all the difference",
//        "I enjoy being surrounded by others",
//        "My fear diminishes as I live my life with courage",
//        "I can go with the flow",
//        "I love myself unconditionally",
//        "I am STRONG",
//        "I allow only healthy and loving relationships into my life",
//        "Life wants the best for me. I am OK with where I am right now",
//        "I am connected and comfortable in all environments, with all people",
//        "I find and enjoy the simple pleasures life is offering right now",
//        "How I feel matters, therefore I concentrate on aspects of life that make me feel good",
//        "My challenges bring me better opportunities",
//        "My mood creates a physiological response in my body. I am peaceful and positive",
//        "I am in control of my thoughts and my life",
//        "I love myself and who I am",
//        "I am happy, healthy, and centered",
//        "Change provides me an opportunity",
//        "I am calm, patient, and in control of my emotions",
//        "The more I give, the more I will receive",
//        "My negative thoughts and self-images are gone",
//        "My strength is stronger than my anxiety",
//        "I move beyond stress to peace",
//        "My thoughts are positive and full of joy",
//        "I am safe. I trust life, and I trust in myself",
//        "My life is an adventure",
//        "Good enough is good enough",
//        "Feelings are not facts",
//        "I have abundant energy",
//        "Let go of “what if”",
//        "Balance in life is what I strive for",
//        "I will take time to put myself first",
//        "I will act after thought, not on instinct",
//        "Calm is my primary state of being",
//        "I am content",
//        "Principles guide me. Not a moments fancy",
//        "I give myself permission to take personal time",
//        "Would I expect this of anyone else",
//        "I am unique and a gift to the world",
//        "Anxiety will not define me",
//        "I am not alone",
//        "I am in control",
//        "I know that this will pass",
//        "I can let go of negative feelings",
//        "I am safe",
//        "I am strong",
//        "I am worthy",
//        "I am loved",
//        "I can get through this",
//        "I do not need to feel scared",
//        "Every breath I take keeps me calm",
//        "I love myself unconditionally",
//        "I look toward the future with hope",
//        "I acknowledge and am prepared for change",
//        "I have peace within me",
//        "I’ve survived this before and will survive again",
//        "I will focus on the beauty around me",
//        "I have the patience to overcome this",
//        "I am in control of my breathing and can slow it down",
//        "It is safe for me to heal and grow",
//        "I will fill my mind with positive thoughts",
//        "I have the power to stop this",
//        "I can solve any problems I may face",
//        "I will attract positive energy",
//        "I am healing more each day",
//        "I choose to focus and be relaxed",
//        "I choose to have a positive reaction to every situation I am faced with",
//        "I will have a serene life",
//        "I can stay calm under pressure",
//        "I will focus on my breathing",
//        "My life is calm",
//        "Everything is okay in my life",
//        "I am better than my anxiety",
//        "I am letting go of my worries",
//        "I will become more relaxed every day",
//        "I can relax my mind",
//        "I deserve to be calm",
//        "I will release all the tension I’m holding in my body",
//        "I am open to the idea that my future will be bright",
//
//    ]
//
    
//    var unfilteredArrayWork : [String] = [
//        "I will work smarter, not harder",
//        "I am a positive influence, and I surround myself with others like me",
//        "Time is my most valuable asset. I guard my time carefully",
//        "Balance is key. I will mix self-care with effort",
//        "My progress is always moving forward",
//        "I feel free to give myself the TLC I need",
//        "Positive energy surrounds me",
//        "I am a wonderful employee. Any company would be lucky to have me",
//        "My career will be the one of my dreams",
//        "When I say “no” to the wrong job, I move that much closer to the perfect career",
//        "My new business income will continue to increase",
//        "I am calm and confident",
//        "New opportunities come easily to me",
//        "I will attract positive customer",
//        "When opportunity knocks, I will be prepared to answer the door",
//        "Money spent comes back to me multiplied",
//        "I have all the power I need to create the success I desire",
//        "The universe provides bountiful opportunities for my success",
//        "I refuse to be distracted from my goals and vision",
//        "Every day is filled with new ideas and new possibilities",
//        "Being successful comes easily to me",
//        "I am worthy of financial stability",
//        "I am open-minded and willing to explore any path to success",
//        "Limiting beliefs have no power over me. I am optimistic and open-minded",
//        "Organization comes naturally to me",
//        "I control my day; I will not let my day control me",
//        "My passion for business brings tangible results",
//        "I will not let others impose their limitations on me",
//        "I am fully committed to achieving success in my life",
//        "My only limit is myself"
//
//    ]
    
}
